from websockets.server import WebSocketServer, WebSocketServerProtocol


class IWebSocketServer:

    def register(self, protocol: 'WebSocketServerProtocol') -> None:...

    # def on_open(self, conn:'WebSocketServerProtocol', handshake): ...

    async def on_error(self, conn:'WebSocketServerProtocol', e: Exception): ...

    async def on_message(self, conn:'WebSocketServerProtocol', message: bytes): ...

    async def on_close(self, conn:'WebSocketServerProtocol'): ...

    async def on_start(self):...